services:
  traefik:
    image: traefik:v2.10
    container_name: traefik_dev
    restart: always
    command:
      - --log.level=DEBUG
      - --accesslog=true
      - --api.dashboard=true
      - --entrypoints.web.address=:80
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --providers.file.filename=/etc/traefik/dynamic.yml
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik/dynamic.yml:/etc/traefik/dynamic.yml:ro
    networks:
      - backend
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.rule=Host(`traefik.${DOMAIN}`)"
      - "traefik.http.routers.traefik.entrypoints=web"
      - "traefik.http.routers.traefik.tls=false"
      - "traefik.http.routers.traefik.middlewares=auth@file"
      - "traefik.http.routers.traefik.service=api@internal"

  gateway:
    build:
      context: ../gateway
      dockerfile: Dockerfile
      target: development
    container_name: gateway_dev
    command: ["npm", "run", "dev"]
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ../gateway:/app
      - /app/node_modules
    depends_on:
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    networks:
      - backend
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.gateway.rule=Host(`api.${DOMAIN}`)"
      - "traefik.http.routers.gateway.entrypoints=web"
      - "traefik.http.routers.gateway.tls=false"

  auth-service:
    build:
      context: ../auth-service
      dockerfile: Dockerfile
      target: development
    container_name: auth-service_dev
    command: ["npm", "run", "dev"]
    restart: always
    depends_on:
      gateway:
        condition: service_started
      redis:
        condition: service_healthy
      mongo:
        condition: service_healthy
    volumes:
      - ../auth-service:/app
      - /app/node_modules
    networks:
      - backend
    labels:
      - "traefik.enable=false"

  redis:
    image: redis:7
    container_name: redis_dev
    restart: always
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    volumes:
      - redis_data_dev:/data
    networks:
      - backend
    labels:
      - "traefik.enable=false"
    healthcheck:
      test: ["CMD-SHELL", "redis-cli -a $REDIS_PASSWORD ping"]
      interval: 90s
      timeout: 30s
      retries: 5
      start_period: 30s

  mongo:
    image: mongo:6.0
    container_name: mongodb_dev
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    volumes:
      - mongodb_data_dev:/data/db
      - ./mongodb/mongo-keyfile:/etc/mongo-keyfile:ro
    command: ["mongod", "--replSet", "rs0", "--bind_ip_all", "--keyFile", "/etc/mongo-keyfile"]
    networks:
      - backend
    labels:
      - "traefik.enable=false"
    healthcheck:
      test: ["CMD-SHELL", 'mongosh --eval ''db.adminCommand("ping").ok'' --quiet || exit 1']
      interval: 10s
      timeout: 10s
      retries: 10

  minio:
    image: minio/minio
    command: server /data --console-address ":9001"
    container_name: minio_dev
    volumes:
      - minio_data_dev:/data
    environment:
      - MINIO_ROOT_USER=${MINIO_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_PASSWORD}
    networks:
      - backend
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.minio-ui.rule=Host(`minio.${DOMAIN}`)"
      - "traefik.http.routers.minio-ui.entrypoints=web"
      - "traefik.http.routers.minio-ui.tls=false"
      - "traefik.http.services.minio-ui.loadbalancer.server.port=9001"

  rabbitmq:
    image: rabbitmq:3.13-management-alpine
    container_name: rabbitmq_dev
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBIT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBIT_PASSWORD}
    volumes:
      - rabbitmq_data_dev:/var/lib/rabbitmq
    networks:
      - backend
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.rabbitmq-ui.rule=Host(`rabbitmq.${DOMAIN}`)"
      - "traefik.http.routers.rabbitmq-ui.entrypoints=web"
      - "traefik.http.routers.rabbitmq-ui.tls=false"
      - "traefik.http.services.rabbitmq-ui.loadbalancer.server.port=15672"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 10

  redisinsight:
    image: redis/redisinsight:latest
    container_name: redisinsight_dev
    environment:
      - REDIS_URI=redis://:${REDIS_PASSWORD}@redis:6379
    depends_on:
      - redis
    networks:
      - backend
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.redisinsight.rule=Host(`redis.${DOMAIN}`)"
      - "traefik.http.routers.redisinsight.entrypoints=web"
      - "traefik.http.routers.redisinsight.tls=false"
      - "traefik.http.routers.redisinsight.middlewares=auth@file"

  mongo-express:
    image: mongo-express
    restart: always
    container_name: mongo-express_dev
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGO_USER}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGO_PASSWORD}
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_BASICAUTH=false
    depends_on:
      - mongo
    networks:
      - backend
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mongoexpress.rule=Host(`mongo.${DOMAIN}`)"
      - "traefik.http.routers.mongoexpress.entrypoints=web"
      - "traefik.http.routers.mongoexpress.tls=false"
      - "traefik.http.routers.mongoexpress.middlewares=auth@file"
      - "traefik.http.services.mongoexpress.loadbalancer.server.port=8081"

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus_dev
    restart: always
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    networks:
      - backend
    labels:
      - "traefik.enable=false"
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.retention.time=15d

  loki:
    image: grafana/loki
    container_name: loki_dev
    restart: always
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - loki_data_dev:/loki
      - ./loki/local-config.yaml:/etc/loki/local-config.yaml:ro
    networks:
      - backend
    labels:
      - "traefik.enable=false"

  alloy:
    image: grafana/alloy:latest
    container_name: alloy_dev
    restart: always
    user: root
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - ./alloy/config.alloy:/etc/alloy/config.alloy:ro
      - ./alloy/positions:/etc/alloy/positions
    command:
      - "run"
      - "--server.http.listen-addr=0.0.0.0:12345"
      - "/etc/alloy/config.alloy"
    networks:
      - backend
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.alloy-ui.rule=Host(`alloy.${DOMAIN}`)"
      - "traefik.http.routers.alloy-ui.entrypoints=web"
      - "traefik.http.routers.alloy-ui.tls=false"
      - "traefik.http.services.alloy-ui.loadbalancer.server.port=12345"
      - "traefik.http.routers.alloy-ui.middlewares=auth@file"

  grafana:
    image: grafana/grafana
    container_name: grafana_dev
    restart: always
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD}
      - GF_AUTH_ANONYMOUS_ENABLED=false
      - GF_SERVER_ROOT_URL=http://grafana.${DOMAIN}
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - grafana_data_dev:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning:ro
    networks:
      - backend
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.grafana.rule=Host(`grafana.${DOMAIN}`)"
      - "traefik.http.routers.grafana.entrypoints=web"
      - "traefik.http.services.grafana.loadbalancer.server.port=3000"
      - "traefik.http.routers.grafana.tls=false"

volumes:
  mongodb_data_dev:
  minio_data_dev:
  redis_data_dev:
  rabbitmq_data_dev:
  grafana_data_dev:
  loki_data_dev:

networks:
  backend:
    driver: bridge
